-- MySQL Script generated by MySQL Workbench
-- Sun Apr 24 23:19:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gcpBackend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gcpBackend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gcpBackend` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gcpBackend` ;

-- -----------------------------------------------------
-- Table `gcpBackend`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcpBackend`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `biografia` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  `gravatar` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gcpBackend`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcpBackend`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_album_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gcpBackend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gcpBackend`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcpBackend`.`picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picture_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_picture_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gcpBackend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gcpBackend`.`album_has_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcpBackend`.`album_has_picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `album_id` INT NOT NULL,
  `picture_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_has_picture_picture1_idx` (`picture_id` ASC) VISIBLE,
  INDEX `fk_album_has_picture_album1_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `fk_album_has_picture_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `gcpBackend`.`album` (`id`),
  CONSTRAINT `fk_album_has_picture_picture1`
    FOREIGN KEY (`picture_id`)
    REFERENCES `gcpBackend`.`picture` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;